controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

formulaire_submit:
    path: '/formulaire/submit'
    controller: App\Controller\FormController::submitAction
    methods: [POST]

handle_form_submission:
    path: /submit
    controller: App\Controller\QuestionnairController::submit
    methods: [POST]

user_dashboard:
    path: '/dashboard'
    controller: 'App\Controller\UserController::dashboard'
    methods: ['GET']

admin_dashboard:
    path: '/admin'
    controller: 'App\Controller\AdminController::dashboard'

app_user_show_answers:
    path: '/user/show-answers/{formTemplateId}'
    controller: 'App\Controller\UserController::showAnswers'
    methods: ['GET']
    requirements:
        formTemplateId: '\d+'
        
app_user_download_responses:
    path: '/user/download-responses/{formTemplateId}/{date}'
    controller: 'App\Controller\PdfController::downloadResponses'
    methods: ['GET']
    requirements:
        formTemplateId: '\d+'

user_show_responses_submit:
    path: /user/user/show-responses/{id}/{date}
    controller: App\Controller\UserController::showResponses
    methods: ['POST']